Technical = {
'MOM_1M': 'short term reversl 1-1 month',
'ZEROTRADE': 'number of zero-trading days (3 months)',
'ME': 'Market Equity',
'STD_DOL_VOL': 'Std of dollar trading volume (3 motnhs)',
'MAXRET': 'maximum daily return',
'ABR': 'abnormal returns around earnings dates',
'BASPREAD': 'bid-ask spread (3m)',
'SEAS1A': 'seaonality',
'BETA': 'Beta (3m)',
'CHCSHO': 'change in shares outstanding',
'RVAR_MEAN': 'return variance (3 month)',
'MOM6M': 'momentum 6 m (2-6 months)',
'DOLVOL': 'dollar trading volume',
'ALM': 'asset liquidity',
'NI': 'net stock issues',
'ATO': 'asset turnover',
'MOM60M': 'long term reversal (13-60 months)',
'MOM36M': 'momemtum 36 m (13-36 month)',
'RVAR_FF3': 'FF3 residual variance (3 month)',
'TURN': 'shares turnover',
'STD_TURN': 'std of share turnover (3 month)',
'MOM12M': 'momentum (2-13 months)',
'RVAR_CAPM': 'CAPM residual variance (3 months)',
'ILL': 'illiquidity (3 months)',
'ME_IA': 'industry-adjusted market equity',
}

Fundamental ={
'SUE': 'unexpected quarterly earnings',
'BM_IA': 'industry adjusted BM',
'BM': 'book to market',
'NOA': 'net operating assets',
'ROA': '',
'CFP': '',
'PM': '',
'LGR': '',
'CASH': '',
'LEV': '',
'RD_SALE': '',
'SP': '',
'EP': '',
'RNA': '',
'AGR': '',
'SGR': '',
'OP': '',
'ROE': '',
'HERF': '',
'ADM': '',
'HIRE': '',
'PSCORE': '',
'DEPR': '',
'DY': '',
'RSUP': '',
'CASHDEBT': '',
'CHPM': '',
'GMA': '',
'PCTACC': '',
'CINVEST': '',
'NINCR': '',
'ACC': '',
'GRLTNOA': '',
'CHTX': ''
}
